<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AyG.Dominio\AyG.Dominio.csproj" />
    <ProjectReference Include="..\AyG.Share\AyG.Share.csproj" />
  </ItemGroup>

</Project>
